// Stamps the build: writes version.json (fetched at runtime with no-store to
// detect new deploys) and src/build-info.ts (compiled into the running app).
// Runs as part of `npm run build`.
import { writeFileSync } from 'node:fs';

const build = new Date().toISOString().replace(/\.\d+Z$/, 'Z');
writeFileSync(new URL('../version.json', import.meta.url), `${JSON.stringify({ build })}\n`);
writeFileSync(
  new URL('../src/build-info.ts', import.meta.url),
  `// Generated by tools/stamp-version.mjs — do not edit.\nexport const BUILD = '${build}';\n`,
);
console.log(`stamped build ${build}`);
